ALERT_CHANNEL_PREFIX = "alerts:"
ALERT_CHANNEL = ALERT_CHANNEL_PREFIX + "{user_id}"
POSITION_CHANNEL = "positions"

ALERT_MESSAGE_TYPE = "geozone_alert"
POSITION_MESSAGE_TYPE = "device_positions"

WS_DISCONNECT_TYPE = "websocket.disconnect"

CLOSE_INVALID_USER = 1008

RESUBSCRIBE_BACKOFF_S = 0.5
RESUBSCRIBE_BACKOFF_MAX_S = 15.0
