x-app: &app
  build:
    context: .
    dockerfile: Dockerfile
  image: geo-device:latest
  env_file:
    - .env
  environment:
    POSTGRES_HOST: postgres
    POSTGRES_PORT: 5432
    REDIS_HOST: redis
    REDIS_PORT: 6379
  networks:
    - geo-device

services:
  postgres:
    image: imresamu/postgis:17-3.5  # todo: change to arm64 build
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: >
      postgres
      -c max_connections=200
      -c shared_buffers=512MB
      -c work_mem=16MB
      -c synchronous_commit=off
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DATABASE}"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
    networks:
      - geo-device

  redis:
    image: redis:7-alpine
    command: >
      redis-server
      --appendonly yes
      --maxmemory 512mb
      --maxmemory-policy noeviction
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 10
    networks:
      - geo-device

  migrate:
    <<: *app
    command: ["migrate"]
    restart: "no"
    depends_on:
      postgres:
        condition: service_healthy

  app:
    <<: *app
    command: ["api"]
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    restart: unless-stopped

networks:
  geo-device:
    driver: bridge

volumes:
  pgdata:
  redisdata:
