STREAM = "pings"
GROUP = "writers"
PAYLOAD_FIELD = b"p"

NEW_MESSAGES = ">"
PENDING_MESSAGES = "0"
GROUP_EXISTS_PREFIX = "BUSYGROUP"

READ_COUNT = 4
BLOCK_MS = 200

POSITION_FLUSH_JITTER_S = 0.25

CLAIM_IDLE_MS = 30_000
CLAIM_INTERVAL_S = 10.0
CLAIM_JITTER_S = 2.0

ZONE_ENTRY_KEY = "inside:{device_id}:{geozone_id}"

RETRY_AFTER_S = 1

RETRY_BACKOFF_S = 0.5
RETRY_BACKOFF_MAX_S = 15.0
